image: registry.gitlab.com/edea-dev/ci-runner:latest


# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/topics/caching/
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - .venv
    - .hypothesis

before_script:
  # For debugging
  - python3 --version 
  - kicad-cli version
  - poetry install
  - git config --global --add safe.directory "$(pwd)"

test:
  script:
    - nox -- --doctest-modules edea --cov=edea
    - nox -- --cov=edea
    - poetry run coverage report
    - poetry run coverage xml
  coverage: "/(?i)total.*? (100(?:\\.0+)?\\%|[1-9]?\\d(?:\\.\\d+)?\\%)$/"
  artifacts:
    when: always
    paths:
      - junit.xml
      - doc-test-junit.xml
    reports:
      junit: 
        - junit.xml
        - doc-test-junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

test long running (project, and sch serialization):
  only:
    - web
  script:
    - git submodule update --init --depth 1
    - poetry run pytest -k 'load_all_kicad_pro' -n auto --junitxml pro.xml
    # the serialize test parses and serializes so we just run that
    - poetry run pytest -k 'serialize_all_sch' -n auto --junitxml sch.xml
  artifacts:
    when: always
    paths:
      - pro.xml
      - sch.xml
    reports:
      junit: 
        - pro.xml
        - sch.xml

test long running (pcb serialization):
  only:
    - web
  script:
    - git submodule update --init --depth 1
    # to avoid running out of server space
    - find tests/kicad_projects/kicad-test-files/ -type f ! -name "*.kicad_pcb" -delete 
    # the serialize test parses and serializes so we just run that
    - poetry run pytest -k 'serialize_all_pcb' -n auto --junitxml pcb.xml
  artifacts:
    when: always
    paths:
      - pcb.xml
    reports:
      junit: 
        - pcb.xml

formatting:
  script:
    - poetry run black --check edea tests --exclude tests/kicad_projects

lint:
  script:
    - poetry run ruff check edea tests --exclude tests/kicad_projects/kicad-test-files
    - poetry run pylint edea
    - poetry run pydoclint edea
    - poetry run sphinx-build -b linkcheck docs docs/_build
    - vale docs


typecheck:
  script:
    - poetry run pyright edea

bandit:
  script:
    - poetry run bandit -r edea

release:
  stage: deploy
  script:
    - poetry build
    - poetry config repositories.gitlab ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi
    - poetry config http-basic.gitlab gitlab-ci-token ${CI_JOB_TOKEN}
    - poetry publish -r gitlab
  artifacts:
    paths:
      - dist/*.whl
  rules:
    - if: $CI_COMMIT_BRANCH == "release"

pages:
  script:
    # download old docs to support multiple versions
    - |
      DOWNLOAD_URL='https://gitlab.com/api/v4/projects/35843774/jobs/artifacts/main/download?job=pages'
      curl -L --output old.zip "$DOWNLOAD_URL"
      unzip -q old.zip -d .

    # build new doccs
    - poetry run sphinx-build -b html docs docs/_build
    ## add new docs to old docs
    - mkdir -p "public/$(poetry version --short)"
    - cp -r docs/_build/* "public/$(poetry version --short)"

    # if the current version of the docs is the latest, copy it to public/latest
    - poetry run python docs/is_latest.py && rm -rf public/latest && mkdir public/latest && cp -r docs/_build/* public/latest || echo "not latest"
    - poetry run python docs/generate_versions.json.py public/versions.json
    - cp docs/_redirects public/_redirects
    - cp docs/_build/sitemap.xml public/sitemap.xml
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "release" || $CI_COMMIT_BRANCH == "pages"

build:nix:
  # https://docs.cachix.org/continuous-integration-setup/gitlab
  image: docker.nix-community.org/nixpkgs/cachix-flakes
  allow_failure: true 

  before_script:
    # We should only execute a single command in this phase, so this overrides the global before_script
    # - mkdir -p "$HOME/.config/nix"
    # - echo 'experimental-features = nix-command flakes' > "$HOME/.config/nix/nix.conf"
    # - nix profile install nixpkgs#cachix  
    - cachix authtoken $CACHIX_TOKEN

  cache: [] 

  variables:
    CACHIX_CACHE_NAME: edea-test-cachix
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

  script:
    - cachix watch-exec $CACHIX_CACHE_NAME -- nix build -L
